"""initial schema

Revision ID: 0337c4c1e967
Revises: 
Create Date: 2026-06-12 18:59:22.407660
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = '0337c4c1e967'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=True)
    op.create_table('knowledge_chunks',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding_reference', sa.String(length=255), nullable=True),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_chunks_source_file'), 'knowledge_chunks', ['source_file'], unique=False)
    op.create_table('threads',
    sa.Column('thread_identifier', sa.String(length=255), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'PENDING', 'CLOSED', 'ESCALATED', name='thread_status'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='thread_priority'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threads_contact_id'), 'threads', ['contact_id'], unique=False)
    op.create_index(op.f('ix_threads_priority'), 'threads', ['priority'], unique=False)
    op.create_index(op.f('ix_threads_status'), 'threads', ['status'], unique=False)
    op.create_index(op.f('ix_threads_thread_identifier'), 'threads', ['thread_identifier'], unique=True)
    op.create_table('emails',
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('message_identifier', sa.String(length=255), nullable=False),
    sa.Column('sender', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emails_message_identifier'), 'emails', ['message_identifier'], unique=True)
    op.create_table('actions',
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'PENDING', 'CLOSED', 'ESCALATED', name='action_status'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actions_status'), 'actions', ['status'], unique=False)
    op.create_table('agent_reasoning_logs',
    sa.Column('email_id', sa.Integer(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('retrieved_chunks', sa.Text(), nullable=False),
    sa.Column('prompt_metadata', sa.Text(), nullable=False),
    sa.Column('classification', sa.Text(), nullable=False),
    sa.Column('reply_draft', sa.Text(), nullable=False),
    sa.Column('execution_plan', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_reasoning_logs_email_id'), 'agent_reasoning_logs', ['email_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('event', sa.Text(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('email_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_email_id'), 'audit_logs', ['email_id'], unique=False)
    op.create_table('classifications',
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('sentiment', sa.String(length=100), nullable=True),
    sa.Column('urgency', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('human_required', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.String(length=1000), nullable=True),
    sa.Column('reply_draft', sa.String(length=4000), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('classifications')
    op.drop_index(op.f('ix_audit_logs_email_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_agent_reasoning_logs_email_id'), table_name='agent_reasoning_logs')
    op.drop_table('agent_reasoning_logs')
    op.drop_index(op.f('ix_actions_status'), table_name='actions')
    op.drop_table('actions')
    op.drop_index(op.f('ix_emails_message_identifier'), table_name='emails')
    op.drop_table('emails')
    op.drop_index(op.f('ix_threads_thread_identifier'), table_name='threads')
    op.drop_index(op.f('ix_threads_status'), table_name='threads')
    op.drop_index(op.f('ix_threads_priority'), table_name='threads')
    op.drop_index(op.f('ix_threads_contact_id'), table_name='threads')
    op.drop_table('threads')
    op.drop_index(op.f('ix_knowledge_chunks_source_file'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_table('contacts')
    op.execute("DROP TYPE IF EXISTS action_status")
    op.execute("DROP TYPE IF EXISTS thread_priority")
    op.execute("DROP TYPE IF EXISTS thread_status")
    # ### end Alembic commands ###
